<?php
/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  SITE / ORGANISATION CONFIGURATION
 * ─────────────────────────────────────────────────────────────────────────────
 *  Normally you do NOT edit this file — run the install wizard (open the site
 *  in a browser) and it writes `site.config.php` for you, including the logo
 *  and brand colours.
 *
 *  This file ships placeholder values and is loaded only as a fallback if
 *  `site.config.php` is missing, so a fresh checkout still boots. To configure
 *  by hand instead of the wizard, copy this to `site.config.php` and edit it.
 * ─────────────────────────────────────────────────────────────────────────────
 */

// ── Organisation identity ─────────────────────────────────────────────────────
define('SITE_NAME_BG', 'Вашата организация');   // name shown on the Bulgarian site
define('SITE_NAME_EN', 'Your Organisation');     // name shown on the English site

// Public base URL — NO trailing slash. Every absolute URL (emails, payment
// callbacks, lang_url()) derives from this.
define('SITE_URL',   'https://example.org');

define('SITE_EMAIL', 'info@example.org');         // public contact / from address
define('SITE_PHONE', '');                         // public phone

// ── Bank details (shown for direct donations; leave '' to hide) ───────────────
define('SITE_IBAN',      '');
define('SITE_BIC',       '');
define('SITE_BANK_NAME', '');

// Email of the single admin account authorised to sign donation certificates.
define('SIGNING_ADMIN_EMAIL', 'info@example.org');

// Purpose line printed on donation certificates (all donations go to your org).
define('DONATION_PURPOSE_BG', 'За дейността и програмите на организацията');
define('DONATION_PURPOSE_EN', 'For the activities and programmes of the organisation');

// ── Brand ─────────────────────────────────────────────────────────────────────
// Primary + accent colours (the wizard sets these; the logo is uploaded to
// assets/images/logo.png). Accent is used for hover/gradient states.
// Visual preset (font + corner shape + default colours): classic | friendly | modern | editorial
define('BRAND_THEME',   'classic');
define('BRAND_PRIMARY', '#0387A5');
define('BRAND_ACCENT',  '#04ADBF');

// ── Social profiles (leave '' to hide that icon) ──────────────────────────────
define('SOCIAL_FACEBOOK',  '');
define('SOCIAL_INSTAGRAM', '');
define('SOCIAL_LINKEDIN',  '');

// ── Analytics / ads (leave '' to disable that tag entirely) ───────────────────
define('GTM_ID',                    '');  // Google Tag Manager container
define('GA4_ID',                    '');  // GA4 measurement ID
define('GOOGLE_ADS_ID',             '');  // Google Ads conversion ID
define('GOOGLE_ADS_PURCHASE_LABEL', '');  // add-to-cart conversion label

// ── Currency ──────────────────────────────────────────────────────────────────
// Bulgaria adopted the Euro on 1 Jan 2026; dual BGN/EUR display is required
// until 1 July 2026. Set DUAL_CURRENCY_UNTIL to a past date for single currency.
define('EUR_BGN_RATE',        1.95583);
define('DUAL_CURRENCY_UNTIL', '2026-07-01');

// ── Optional feature modules ──────────────────────────────────────────────────
// Crowdfunding campaigns (the campaign/ pages + reward pledges in checkout).
define('FEATURE_CAMPAIGN', true);
