<?php
/**
 * The install itself, run from install/index.php when "Инсталирай" is pressed
 * on the last step. Uses $done (every step's answers), $cpanel and $ROOT; sets
 * $success, $install_error, $logo_note and $done_final.
 *
 * Order matters: db.config.php first (migrate.php reads it), then tables and
 * the admin, and site.config.php only once all of that worked — the wizard
 * locks itself as soon as both config files exist, so a failure part-way must
 * leave it open for another try.
 */

if (!isset($done, $ROOT) || wizard_first_open_step($done) !== 'review') {
    return;
}

$db = $done['db'];

// ── The database: create it on cPanel, or use the one given ──────────────────
if ($db['db_mode'] === 'create') {
    if (!$cpanel) {
        $install_error = 'Този сървър не позволява автоматично създаване на база данни. Върнете се на стъпка 1 и въведете данните от хостинга.';
        return;
    }
    $account  = get_current_user();   // the cPanel account user
    $existing = uapi('Mysql', 'list_databases', []);
    $names    = array_column(is_array($existing['data']) ? $existing['data'] : [], 'database');
    $name     = wizard_pick_db_name($account, $names);
    $pass     = bin2hex(random_bytes(12));
    foreach ([
        ['create_database',            ['name' => $name],                                                        'базата данни'],
        ['create_user',                ['name' => $name, 'password' => $pass],                                   'потребителя на базата данни'],
        ['set_privileges_on_database', ['user' => $name, 'database' => $name, 'privileges' => 'ALL PRIVILEGES'], 'правата на потребителя'],
    ] as [$func, $args, $what]) {
        $r = uapi('Mysql', $func, $args);
        if (!$r['ok']) {
            $install_error = 'Не успяхме да създадем ' . $what . ' в cPanel. Опитайте отново след минута; ако пак не стане, '
                           . 'върнете се на стъпка 1 и изберете „Вече имам база данни“. Техническа информация: ' . implode('; ', (array) $r['errors']);
            return;
        }
    }
    $db = ['db_mode' => 'create', 'db_host' => 'localhost', 'db_name' => $name, 'db_user' => $name, 'db_pass' => $pass];
    // Remember it, so a retry after a later failure reuses this database instead of making another.
    $_SESSION['install']['done']['db'] = ['db_mode' => 'existing'] + $db;
}

try {
    $pdo = new PDO('mysql:host=' . $db['db_host'] . ';dbname=' . $db['db_name'] . ';charset=utf8mb4',
        $db['db_user'], $db['db_pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
} catch (PDOException $ex) {
    $install_error = 'Базата данни не отговаря. Върнете се на стъпка 1 и проверете данните. Техническа информация: ' . $ex->getMessage();
    return;
}

$db_config = $ROOT . '/db.config.php';
if (!write_config($db_config, [
    'DB_HOST' => $db['db_host'],
    'DB_NAME' => $db['db_name'],
    'DB_USER' => $db['db_user'],
    'DB_PASS' => $db['db_pass'],
    'SETTINGS_ENCRYPTION_KEY' => bin2hex(random_bytes(32)),
], 'Database connection — generated by the install wizard.')) {
    $install_error = 'Не успяхме да запишем настройките на сървъра. Проверете дали папката на сайта позволява запис (права 755).';
    return;
}

// migrate.php defines run_migrations() and only runs itself from the CLI.
require_once $ROOT . '/migrate.php';
ob_start();
$migration_result = run_migrations();
ob_end_clean();
if (!$migration_result['success']) {
    @unlink($db_config);
    $install_error = 'Не успяхме да създадем таблиците в базата данни. Техническа информация: ' . ($migration_result['error'] ?? 'неизвестна грешка');
    return;
}

$account = $done['account'];
try {
    if ((int) $pdo->query('SELECT COUNT(*) FROM admin_users')->fetchColumn() === 0) {
        $pdo->prepare('INSERT INTO admin_users (name, email, password_hash, role) VALUES (?,?,?,\'admin\')')
            ->execute([$account['admin_name'] ?: 'Администратор', $account['admin_email'], $account['password_hash']]);
    }
} catch (Throwable $ex) {
    @unlink($db_config);
    $install_error = 'Таблиците са създадени, но профилът ви не можа да бъде добавен. Техническа информация: ' . $ex->getMessage();
    return;
}

if (!write_config($ROOT . '/site.config.php', wizard_site_config($done),
    'Organisation configuration — generated by the install wizard. Edit freely. FEATURE_* are only initial values: the switches in Admin → Модули win over them.')) {
    @unlink($db_config);
    $install_error = 'Не успяхме да запишем настройките на сървъра. Проверете дали папката на сайта позволява запис (права 755).';
    return;
}

// The logo was checked and re-encoded at step 4; a failed copy must not undo the install.
if ($logo = staged_logo()) {
    $images = $ROOT . '/assets/images';
    if (!@copy($logo, $images . '/logo.png')) {
        $logo_note = 'Логото не беше запазено. Сайтът работи с неутрален знак — качете логото си от администраторския панел → „Организация“.';
    } else {
        @copy(dirname($logo) . '/favicon.png', $images . '/favicon.png');
    }
    @unlink(dirname($logo) . '/favicon.png');
    @unlink($logo);
    @rmdir(dirname($logo));
}

$success    = true;
$done_final = $done;
$_SESSION['install'] = null;   // nothing (database password included) outlives the install
session_destroy();
